apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
    version: 0.0.2
spec:
  selector:
    app: eureka-server
  type: LoadBalancer      
  ports:
  - name: tcp-8761-8761
    protocol: TCP
    port: 8761
    targetPort: 8761
