apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
    version: 0.0.2
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: 192.168.1.211:5000/k8s-ci:gateway-0.0.2
        imagePullPolicy: Always
        env:
        - name: eureka_host
          value: "eureka.default.svc.cluster.local"
        - name: eureka_port
          value: "8761"