apiVersion: v1
kind: Service
metadata:
  name: gateway-lb
  labels:
    app: gateway-lb
    version: 0.0.2
spec:
  selector:
    app: gateway
  type: LoadBalancer      
  ports:
  - name: tcp-80-80
    protocol: TCP
    port: 80
    targetPort: 80
